### ISSUE TITLE
An incorrect version number is indicated on this page

### ISSUE THREAD

**Issue by DAnn2012** [neooffice/NeoOffice#12]
Hello @plubius 

Please note that an incorrect version number is indicated on this page:

https://github.com/neooffice/NeoOffice/releases/tag/NeoOffice-2022_3

![neo2022-3](https://user-images.githubusercontent.com/1197819/194594051-e682fb37-1b1e-4cd8-b1c2-bfc68967f416.png)

Thanks.

**Comment by neooffice** [comment]
Typo corrected.
