### ISSUE TITLE
"Could not create Java implementation loader"

### ISSUE THREAD

**Issue by ondohotola** [neooffice/NeoOffice#15]
on Ventura M1 I installed  [Oracle JDK 17 ARM 64](https://www.oracle.com/java/technologies/downloads/#jdk19-mac) as directed and then NeoOffice 2022.5 Professional Edition.

When trying to install (or rather to enable the writer2latex.oxt I get the above error.

When I go to Options -> Advanced Java is enabled but no JRE is found.

On my Monterey Intel it worked with the [Oracle JDK 8](http://www.neooffice.org/neojava/javadownload.php).

I have reinstalled, rebooted but still get this error.

Is there a way of manually configuring the path to the JRE?

**Comment by plubius** [comment]
One other thing to try: if you have Oracle JDK 19 installed, open the following file:

sudo <your favorite text editor> /Applications/NeoOffice.app/Contents/Resources/ure/share/misc/javavendors.xml

...and replace the line with the <maxVersion> tag with the following line:

<maxVersion>19.999.999</maxVersion>

...and restart NeoOffice. The above should make Oracle JDK 19 findable by NeoOffice.

**Comment by ondohotola** [comment]
```
Matching Java Virtual Machines (1):
    19.0.1 (arm64) "Oracle Corporation" - "Java SE 19.0.1" /Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home
```

**Comment by ondohotola** [comment]
`sudo mate /Applications/NeoOffice.app/Contents/Resources/ure/share/misc/javavendors.xml`

does the trick :-)-O

thank you very much :-)-O

**Comment by plubius** [comment]
I am leaving a reminder for myself: enable JDK 19 in the next patch or release.

Oracle's website appears to encourage downloading JDK 19 so, instead of restricting the JDK version, maybe it is better to remove the <maxVersion> so that users can use the latest JDK version.

**Comment by ondohotola** [comment]
Thank you very much

el

On 08/12/2022 15:53, PL wrote:
> I am leaving a reminder for myself: enable JDK 19 in the next patch or
> release.
> 
> Oracle's website appears to encourage downloading JDK 19 so, instead of
> restricting the JDK version, maybe it is better to remove the so that
> users can use the latest JDK version.
[...]

-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply

**Comment by plubius** [comment]
I have posted a patch that removes the <maxVersion> line in the javavendors.xml file for anyone who doesn't want to edit that file directly. I will also include this change in the next NeoOffice release:

- [NeoOffice 2022.5 Professional Edition](https://github.com/neooffice/NeoOffice/releases/download/NeoOffice-2022_5/NeoOffice-2022.5_Professional_Edition-Patch-0-JDK_19-Universal.dmg)

**Comment by ondohotola** [comment]
Thank you.

el

On 09/12/2022 17:04, PL wrote:
> I have posted a patch that removes the line in the
> javavendors.xml file for anyone who doesn't want to edit that
> file directly.  I will also include this change in the next
> NeoOffice release:[...]

-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply
