### ISSUE TITLE
Cursor blinking

### ISSUE THREAD

**Issue by yosamsimiti** [neooffice/NeoOffice#16]
Is there any way to adjust the cursor blinking, so that it simply doesn’t blink?  The typical solution is go through the terminal app and adjust the cursor blink rate.  Unfortunately, it works only for in-house Mac apps, and doesn’t work for NeoOffice, Libreoffice or open office.  Is there any way to make the cursor not blink like they don’t in all my other apps?

**Comment by plubius** [comment]
I do not know of any setting in NeoOffice's underlying LibreOffice code that will stop the cursor from blinking. But you can simulate it by setting the macOS blink rate to a very high number. For example, if you execute the following Terminal command and restart NeoOffice, the cursor will only blink every 1000 seconds (1 000 000 milliseconds):

defaults write -g NSTextInsertionPointBlinkPeriod -integer 1000000

**Comment by yosamsimiti** [comment]
Yeah I have tried that.  Doesn't work for neooffice.  Everything except libreoffice, neooffice or OpenOffice works with the defaults command.  But for neooofice the cursor blinks and blinks and blinks and blinks...it's driving me crazy haha.

**Comment by yosamsimiti** [comment]
Actually never mind.  It took a couple of restarts for the change to finally detect the change for some reason.  All is well with the world, thanks so much!
