### ISSUE TITLE
text color not applied in calc

### ISSUE THREAD

**Issue by barredespace** [neooffice/NeoOffice#17]
NeoOffice 2022.5
When assigning a color to text for a cell or a group of cells, text color stays default. Text color is displayed if text is edited in cell.
Tried with custom colors > font color set to automatic or black.

**Comment by plubius** [comment]
I cannot reproduce what you see on my Silicon Mac. Whether I select a group of cells or just some text within a single cell, the custom color I select takes effect immediately after closing the custom color dialog.

If you select a group of cells and then select the Format > Clear Direct Formatting menu and then apply a custom font color, does the bug still occur for you?

**Comment by barredespace** [comment]
Thanks for your answer. And yes, the bug still occurs when I do what you suggested.
Here are my specs : MacBook Pro 16'' 2019 (intel) MacOS 12.6.3
And a quick video for you to see what it looks like : https://sendvid.com/mdbap7by

**Comment by plubius** [comment]
Does this occur in all your spreadsheets, even a new empty one? If yes, you might want to reset your NeoOffice preference files with default values using the steps in the following link:

NeoOffice's https://neowiki.neooffice.org/index.php/NeoOffice_2022_Upgrade_Issues#Step_5_-_If_NeoOffice_crashes_or_does_not_save.2C_try_these_steps

Does resetting your NeoOffice preferences change anything?

**Comment by barredespace** [comment]
It did occur in all my spreadsheets even empty ones but resetting preferences did the trick and everything is fine now. Thanks.
