### ISSUE TITLE
Changing any cells within the data range of a Calc chart causes text color to invert when saving

### ISSUE THREAD

**Issue by plubius** [neooffice/NeoOffice#2]
This bug only occurs while running NeoOffice in Dark Mode. By default, charts use a dark color for the default text color. But if any cells within a chart's data range are edited. Saving the Calc document will flip the chart's text to a light color until the file is reloaded.

**Comment by plubius** [comment]
The fix for this bug is in the NeoOffice_Developer_Build-2022_Developer_Preview-Patch-0-Test-1-Universal.dmg test patch

**Comment by neooffice** [comment]
The fix for this bug is in the NeoOffice 2022 release.
