### ISSUE TITLE
Hang when changing font while there is uncommitted text in a Writer comment

### ISSUE THREAD

**Issue by plubius** [neooffice/NeoOffice#3]
When entering text in a Writer comment and the entered text is uncommitted, changing the font in Writer's font dropdown list will cause the macOS input method to go into an infinite loop.

I can reproduce this bug on macOS 12.3.1 with the following system input methods:
- Hiragana:entering "a" repeatedly 
- Canjie -Traditional entering "p" repeatedly

This bug was originally reported in [LibreOffice issue 82115](https://bugs.documentfoundation.org/show_bug.cgi?id=82115).

**Comment by plubius** [comment]
Correction: my steps to reproduce were incomplete. Here are the correct steps:
- Hiragana:entering "a" 3 times, change font, press "a" again, NeoOffice hangs
- Canjie -Traditional entering "p" 3 times, change font, press "p" again, NeoOffice hangs

Attached is [Sample of NeoOffice Developer Build.txt](https://github.com/neooffice/NeoOffice/files/8619968/Sample.of.NeoOffice.Developer.Build.txt) taken in the Activity Monitor application. At first glance, it looks like there is an infinite loop in the LibreOffice code, not the macOS input method:

**Comment by plubius** [comment]
The fix for this bug is in the NeoOffice_Developer_Build-2022_Developer_Preview-Patch-0-Test-2-Universal.dmg test patch

**Comment by neooffice** [comment]
The fix for this bug is in the NeoOffice 2022 release.

**Comment by plubius** [comment]
The improved fix is in the NeoOffice 2022 Test 2 patches.

**Comment by plubius** [comment]
The improved fix is included in the NeoOffice 2022.1:
- [NeoOffice 2022.1 Professional Edition](https://github.com/neooffice/NeoOffice/releases/latest)
- [NeoOffice 2022.1 in the Mac App Store](https://apps.apple.com/app/neooffice/id639210716?mt=12)
